### ISSUE TITLE
Unclear error message when colons are not preceded by a space

### ISSUE THREAD

**Issue by erwann-met** [jsh9/pydoclint#37] opened 2023-06-29 14:39 UTC
Here is the code to reproduce the issue:
![image](https://github.com/jsh9/pydoclint/assets/113345860/2dba0d27-c510-4d3b-aee2-3486f2d01bba)

Here is the error raised by `pydoclint`:

![image](https://github.com/jsh9/pydoclint/assets/113345860/25aed1ae-3863-47eb-b17e-468782a44e2a)
Here the 2 error messages do not indicate the root cause: lack of a space before the colons in the docstrings.

A good first fix would be to add that these errors could be triggered by the lack of a space before the colons.
Ideally, this should be detected.

**Comment by jsh9** [comment] 2023-06-30 05:49
Thanks for reporting this!

The root cause is: pydoclint uses [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html), the official numpy docstring library, to parse numpy-style docstrings.

The official numpy-style docstring format requires a space between the argument name and the colon (`:`).  Without that space, the parser parses the whole `a: int` as a whole argument.

If you read the error message of DOC103, I said "Or could be other formatting issues: https://github.com/jsh9/pydoclint#notes-on-doc103").  In the link, I mentioned this case.

I don't really have a very good solution here, since it's probably not feasible or recommended to "hack into" numpydoc's internal code.

Do you have any suggestions?

**Comment by jsh9** [comment] 2023-07-20 07:57
Closing this issue. No actions needed.

(If I closed this issue by accident, please feel free to leave a comment here.)

**Closed by jsh9** 2023-07-20 07:57 UTC
