### ISSUE TITLE
Unclear error messages when sections are not separated with white lines

### ISSUE THREAD

**Issue by erwann-met** [jsh9/pydoclint#36] opened 2023-06-29 14:33 UTC
Here is the sample code to reproduce this issue
![image](https://github.com/jsh9/pydoclint/assets/113345860/2b53138e-d3ab-4b69-88ce-9ab753718608)

Note that despite of the rule `D410` from `ruff`, the lack of a white line before the `Returns` section is not detected. (Issue on `ruff` as well)
![image](https://github.com/jsh9/pydoclint/assets/113345860/650cf822-a71d-4bb8-9e40-f1ee5c4ed7e8)

When running `pydoclint`, the error message is unclear:
![image](https://github.com/jsh9/pydoclint/assets/113345860/424b5ae0-4f64-4257-94f6-c7462540f636)

4 error codes are returned, none describing the actual root cause (lack of a white line between sections)

Note that this would not be an issue if `D410` from ruff had worked so maybe not a priority.

**Comment by erwann-met** [comment] 2023-06-29 15:16
Related issue on `ruff`: https://github.com/astral-sh/ruff/issues/5442

**Comment by jsh9** [comment] 2023-06-30 05:45
Thanks for reporting this!  Very interesting case.

The root cause is: pydoclint uses [numpydoc](https://numpydoc.readthedocs.io/en/latest/format.html), the official numpy docstring library, to parse numpy-style docstrings.  Without the blank line before `Returns`, the parser thinks that there isn't a return section, and `--------` and `Returns:` are actually input arguments.

Please note that the use of numpydoc in pydoclint is probably one of the reason that it's much faster than darglint.  (I think darglint's author implemented a custom docstring parser.)

It's probably not feasible for pydoclint to "hack into" numpydoc's internal code.

Do you have suggestions of a solution?

**Comment by erwann-met** [comment] 2023-06-30 08:00
I think that as soon as ruff rule `D410` is fixed, this should not be an issue any more.
This might be out of the scope of `pydoclint` indeed.

**Comment by jsh9** [comment] 2023-07-20 07:57
Closing this issue.  No actions needed.

(If I closed this issue by accident, please feel free to leave a comment here.)

**Closed by jsh9** 2023-07-20 07:57 UTC
